version: '3'
services:
  web:
    stdin_open: true
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./client:/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./api:/app
  nginx:
    restart: always
    depends_on: 
      - api
      - web
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"